# Generated by Django 4.2.17 on 2024-12-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='matched_skills_count',
        ),
    ]
